[
  "mountain",
  "arms lifted",
  "forward fold",
  "half up",
  "forward fold",
  "lunge",
  "nose to knee",
  "plank",
  "Chaturanga",
  "up dog",
  { sides: [
    "down dog",
    "kick leg",
    "wild thing",
    "down dog",
    "lunge",
    "Warrior 1",
    "Warrior 2",
    "reverse warrior",
    "triangle",
    "Warrior 2",
    "lunge"]
    },
  "nose to knee",
  "down dog",
  "through",
  "boat",
  "reverse plank",
  "side plank",
  "plank",
  "chaturanga",
  "up dog",
  "down dog",
  "folding",
  "arms lifted"
]